[package]
name = "smolstc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
network-p2p = {git = "https://github.com/starcoinorg/starcoin"}