[package]
name = "smolstc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members=[
    "consensus",
]

default-members = [
    "consensus",
]
[dependencies]
starcoin-network = {git = "https://github.com/starcoinorg/starcoin"}
starcoin-logger = {git = "https://github.com/starcoinorg/starcoin"}
starcoin-config = {git = "https://github.com/starcoinorg/starcoin"}
